name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEPLOY_ENV: RELEASE

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with:
          ref: main

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-v2

      - name: Install dependencies
        run: yarn

      - name: Generate sites
        run: yarn build

      - name: Git and SSH configurations
        env:
          DEPLOYKEY: ${{ secrets.SPORTS_PRIVATE_DEPLOYKEY }}
        run: |
          echo "$DEPLOYKEY" > ~/deploykey.pem
          chmod 600 ~/deploykey.pem
          git config --global user.email "digital@nada-sc.jp"
          git config --global user.name "Github Actions"

      - name: Push pages
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploykey.pem -o StrictHostKeyChecking=no -F /dev/
        run: |
          git clone git@github.com:NadaDigitalCommittee/SportsPublic.git
          cd SportsPublic
          mkdir ../old
          ls ./ | grep -v -E '.git|2023' | xargs -i mv {} ../old
          ls ./ | grep -v -E '^.git' | xargs rm -r
          mkdir ./2023
          mv ../out/* ./2023
          mv ../old/* ./
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Deploy NadaDigitalCommittee/Sports2023@$GITHUB_SHA"
            git push origin main
          fi
